//Author	:		Mohamed Gamal Eleish
//Date		:		12/10/2020
//Version	:		V01


#ifndef DMA_CONFIG_H
#define DMA_CONFIG_H

#define DMA_CHANNEL1_ENABLED							DMA_DISABLED
#define DMA_CHANNEL2_ENABLED							DMA_ENABLED
#define DMA_CHANNEL3_ENABLED							DMA_DISABLED
#define DMA_CHANNEL4_ENABLED							DMA_DISABLED
#define DMA_CHANNEL5_ENABLED							DMA_DISABLED
#define DMA_CHANNEL6_ENABLED							DMA_DISABLED
#define DMA_CHANNEL7_ENABLED							DMA_DISABLED


/*Channel 1 Configuration*/
#define DMA_CH1_MEMMORY_TO_MEMORY_MODE				DMA_ENABLED
#define DMA_CH1_CHANNEL_PRIORITY					DMA_VERY_HIGH
#define DMA_CH1_MEMORY_SIZE							DMA_32_BITS
#define DMA_CH1_PERIPHERAL_SIZE						DMA_32_BITS
#define DMA_CH1_MEMORY_INC							DMA_ENABLED
#define DMA_CH1_PERIPHERAL_INC						DMA_ENABLED
#define DMA_CH1_CIRCULAR_MODE						DMA_DISABLED
#define DMA_CH1_DATA_TRANSFER_DIRECTION				DMA_READ_FROM_PERIPHERAL
#define DMA_CH1_TRANSFER_ERROR_INTERRUPT			DMA_DISABLED
#define DMA_CH1_HALF_TRANSFER_INTERRUPT				DMA_ENABLED
#define DMA_CH1_TRANSFER_COMPLETED_INTERRUPT		DMA_DISABLED


/*Channel 2 Configuration*/
#define DMA_CH2_MEMMORY_TO_MEMORY_MODE				DMA_ENABLED
#define DMA_CH2_CHANNEL_PRIORITY					DMA_VERY_HIGH
#define DMA_CH2_MEMORY_SIZE							DMA_32_BITS
#define DMA_CH2_PERIPHERAL_SIZE						DMA_32_BITS
#define DMA_CH2_MEMORY_INC							DMA_ENABLED
#define DMA_CH2_PERIPHERAL_INC						DMA_ENABLED
#define DMA_CH2_CIRCULAR_MODE						DMA_DISABLED
#define DMA_CH2_DATA_TRANSFER_DIRECTION				DMA_READ_FROM_PERIPHERAL
#define DMA_CH2_TRANSFER_ERROR_INTERRUPT			DMA_DISABLED
#define DMA_CH2_HALF_TRANSFER_INTERRUPT				DMA_ENABLED
#define DMA_CH2_TRANSFER_COMPLETED_INTERRUPT		DMA_DISABLED


/*Channel 3 Configuration*/
#define DMA_CH3_MEMMORY_TO_MEMORY_MODE				DMA_ENABLED
#define DMA_CH3_CHANNEL_PRIORITY					DMA_VERY_HIGH
#define DMA_CH3_MEMORY_SIZE							DMA_32_BITS
#define DMA_CH3_PERIPHERAL_SIZE						DMA_32_BITS
#define DMA_CH3_MEMORY_INC							DMA_ENABLED
#define DMA_CH3_PERIPHERAL_INC						DMA_ENABLED
#define DMA_CH3_CIRCULAR_MODE						DMA_DISABLED
#define DMA_CH3_DATA_TRANSFER_DIRECTION				DMA_READ_FROM_PERIPHERAL
#define DMA_CH3_TRANSFER_ERROR_INTERRUPT			DMA_ENABLED
#define DMA_CH3_HALF_TRANSFER_INTERRUPT				DMA_DISABLED
#define DMA_CH3_TRANSFER_COMPLETED_INTERRUPT		DMA_ENABLED


/*Channel 4 Configuration*/
#define DMA_CH4_MEMMORY_TO_MEMORY_MODE				DMA_ENABLED
#define DMA_CH4_CHANNEL_PRIORITY					DMA_VERY_HIGH
#define DMA_CH4_MEMORY_SIZE							DMA_32_BITS
#define DMA_CH4_PERIPHERAL_SIZE						DMA_32_BITS
#define DMA_CH4_MEMORY_INC							DMA_ENABLED
#define DMA_CH4_PERIPHERAL_INC						DMA_ENABLED
#define DMA_CH4_CIRCULAR_MODE						DMA_DISABLED
#define DMA_CH4_DATA_TRANSFER_DIRECTION				DMA_READ_FROM_PERIPHERAL
#define DMA_CH4_TRANSFER_ERROR_INTERRUPT			DMA_ENABLED
#define DMA_CH4_HALF_TRANSFER_INTERRUPT				DMA_DISABLED
#define DMA_CH4_TRANSFER_COMPLETED_INTERRUPT		DMA_ENABLED


/*Channel 5 Configuration*/
#define DMA_CH5_MEMMORY_TO_MEMORY_MODE				DMA_ENABLED
#define DMA_CH5_CHANNEL_PRIORITY					DMA_VERY_HIGH
#define DMA_CH5_MEMORY_SIZE							DMA_32_BITS
#define DMA_CH5_PERIPHERAL_SIZE						DMA_32_BITS
#define DMA_CH5_MEMORY_INC							DMA_ENABLED
#define DMA_CH5_PERIPHERAL_INC						DMA_ENABLED
#define DMA_CH5_CIRCULAR_MODE						DMA_DISABLED
#define DMA_CH5_DATA_TRANSFER_DIRECTION				DMA_READ_FROM_PERIPHERAL
#define DMA_CH5_TRANSFER_ERROR_INTERRUPT			DMA_ENABLED
#define DMA_CH5_HALF_TRANSFER_INTERRUPT				DMA_DISABLED
#define DMA_CH5_TRANSFER_COMPLETED_INTERRUPT		DMA_ENABLED


/*Channel 6 Configuration*/
#define DMA_CH6_MEMMORY_TO_MEMORY_MODE				DMA_ENABLED
#define DMA_CH6_CHANNEL_PRIORITY					DMA_VERY_HIGH
#define DMA_CH6_MEMORY_SIZE							DMA_32_BITS
#define DMA_CH6_PERIPHERAL_SIZE						DMA_32_BITS
#define DMA_CH6_MEMORY_INC							DMA_ENABLED
#define DMA_CH6_PERIPHERAL_INC						DMA_ENABLED
#define DMA_CH6_CIRCULAR_MODE						DMA_DISABLED
#define DMA_CH6_DATA_TRANSFER_DIRECTION				DMA_READ_FROM_PERIPHERAL
#define DMA_CH6_TRANSFER_ERROR_INTERRUPT			DMA_ENABLED
#define DMA_CH6_HALF_TRANSFER_INTERRUPT				DMA_DISABLED
#define DMA_CH6_TRANSFER_COMPLETED_INTERRUPT		DMA_ENABLED


/*Channel 7 Configuration*/
#define DMA_CH7_MEMMORY_TO_MEMORY_MODE				DMA_ENABLED
#define DMA_CH7_CHANNEL_PRIORITY					DMA_VERY_HIGH
#define DMA_CH7_MEMORY_SIZE							DMA_32_BITS
#define DMA_CH7_PERIPHERAL_SIZE						DMA_32_BITS
#define DMA_CH7_MEMORY_INC							DMA_ENABLED
#define DMA_CH7_PERIPHERAL_INC						DMA_ENABLED
#define DMA_CH7_CIRCULAR_MODE						DMA_DISABLED
#define DMA_CH7_DATA_TRANSFER_DIRECTION				DMA_READ_FROM_PERIPHERAL
#define DMA_CH7_TRANSFER_ERROR_INTERRUPT			DMA_ENABLED
#define DMA_CH7_HALF_TRANSFER_INTERRUPT				DMA_DISABLED
#define DMA_CH7_TRANSFER_COMPLETED_INTERRUPT		DMA_ENABLED


#endif

