//Author		:	Mohamed Gamal Eleish
//Date			:	15/10/2020
//Version 		:	V01




#ifndef SPI_CONFIG_H
#define SPI_CONFIG_H

#define SPI1_BIDIRECTIONAL_MODE			SPI_DISABLED
#define SPI1_BIDIRECTIONAL_DATA_MAODE	SPI_DISABLED
#define SPI1_CRC						SPI_DISABLED
#define SPI1_DATA_FORMAT				SPI_8_BITS_FORMAT
#define SPI1_RECEIVE_ONLY				SPI_DISABLED
#define SPI1_SLAVE_MANGEMENT			SPI_SOFTWARE_CONTROL
#define SPI1_DATA_TRANSMIT_MODE			SPI_MSB_FIRST
#define SPI1_BAUD_RATE_PRESCALAR		SPI_DIV_2
#define SPI1_MODE						SPI_MASTER
#define SPI1_IDLE_STATE					SPI_IDLE_HIGH
#define SPI1_SEQUENCE					SPI_WRITE_READ

#endif

