




#ifndef LED_MTRX_CONFIG_H
#define LED_MTRX_CONFIG_H

/*Please write pair PORT,PIN*/

#define LED_MTRX_ROW0_PIN		PORTA,0
#define LED_MTRX_ROW1_PIN		PORTA,1
#define LED_MTRX_ROW2_PIN		PORTA,2
#define LED_MTRX_ROW3_PIN		PORTA,3
#define LED_MTRX_ROW4_PIN		PORTA,4
#define LED_MTRX_ROW5_PIN		PORTA,5
#define LED_MTRX_ROW6_PIN		PORTA,6
#define LED_MTRX_ROW7_PIN		PORTA,7

#define LED_MTRX_COL0_PIN		PORTB,0
#define LED_MTRX_COL1_PIN		PORTB,1
#define LED_MTRX_COL2_PIN		PORTB,5
#define LED_MTRX_COL3_PIN		PORTB,6
#define LED_MTRX_COL4_PIN		PORTB,7
#define LED_MTRX_COL5_PIN		PORTB,8
#define LED_MTRX_COL6_PIN		PORTB,9
#define LED_MTRX_COL7_PIN		PORTB,10


#endif