//Author		:		Mohamed G. Eleish
//Date			:		16/10/2020
//Version		:		V01



#ifndef	USART1_CONFIG_H
#define USART1_CONFIG_H

#define USART1_BAUD_RATE					9600UL

#define USART1_BUS_CLOCK					8000000UL

#define USART1_WORD_LENGTH					USART1_8_BITS

#define USART1_PARITY_CONTROLE				USART1_DISABLED

#define USART1_STOP_BITS					USART1_1_BIT

#define USART1_CLK_PIN						USART1_DISABLED

#define USART1_MODE							USART1_ASYNCHRONOUS

#define USART1_IDLE_STATE					USART1_IDLE_HIGH

#define USART1_SEQUENCE						USART1_SETUP_THEN_READ

#define USART1_DMA_TRANSMITTER				USART1_DISABLED

#define USART1_DMA_RECEIVER					USART1_DISABLED

#endif

